apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar-backend
spec:
  selector:
    matchLabels:
      app: sonar-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: sonar-backend
    spec:
      containers:
        - name: sonar
          image: "sonar:latest"
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9000
              name: grpc
          env:
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: infra-config
                  key: rmq-url
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: infra-config
                  key: rmq-port
            - name: SONAR_MODE
              value: backend
            - name: SONAR_BACKEND_DISTANCE_CONSUMER_ENABLED
              value: "true"
            - name: SONAR_BACKEND_DISTANCE_QUEUE_NAME
              value: sonar.distance.backend
            - name: GRPC_PORT
              value: "9000"
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            requests:
              memory: "160Mi"
              cpu: "100m"
            limits:
              memory: "320Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: sonar-backend
spec:
  type: ClusterIP
  selector:
    app: sonar-backend
  ports:
    - port: 8080
      targetPort: 8080
      name: http
    - port: 9000
      targetPort: 9000
      name: grpc