# Database
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME:dse}
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD:dse}
quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL:jdbc:postgresql://localhost:5432/orchestrator}
quarkus.hibernate-orm.schema-management.strategy=${HIBERNATE_SCHEMA_STRATEGY:drop-and-create}

# UTRACKED REST client
quarkus.rest-client.utracked-api.url=${UTRACKED_URL:http://localhost:8086}

# RabbitMQ
rabbitmq-host=${RABBITMQ_HOST:localhost}
rabbitmq-port=${RABBITMQ_PORT:5672}
rabbitmq-username=${RABBITMQ_USERNAME:dse}
rabbitmq-password=${RABBITMQ_PASSWORD:dse}

mp.messaging.incoming.vehicle-distance.connector=smallrye-rabbitmq
mp.messaging.incoming.vehicle-distance.exchange.name=d2s.vehicle.distance
mp.messaging.incoming.vehicle-distance.exchange.type=topic
mp.messaging.incoming.vehicle-distance.queue.name=orchestrator.distance
mp.messaging.incoming.vehicle-distance.routing-key=distance.#

mp.messaging.outgoing.brake-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.brake-out.exchange.name=d2s.vehicle.brake
mp.messaging.outgoing.brake-out.exchange.type=topic
mp.messaging.outgoing.brake-out.routing-key=brake

mp.messaging.incoming.brake-in.connector=smallrye-rabbitmq
mp.messaging.incoming.brake-in.exchange.name=d2s.vehicle.brake
mp.messaging.incoming.brake-in.exchange.type=topic
mp.messaging.incoming.brake-in.queue.name=orchestrator.brake
mp.messaging.incoming.brake-in.routing-key=brake.#

mp.messaging.incoming.scenario-command.connector=smallrye-rabbitmq
mp.messaging.incoming.scenario-command.exchange.name=d2s.simulator.scenario
mp.messaging.incoming.scenario-command.exchange.type=fanout
mp.messaging.incoming.scenario-command.queue.name=${ORCHESTRATOR_SCENARIO_QUEUE_NAME:orchestrator.scenario}
mp.messaging.incoming.scenario-command.routing-key=scenario

orchestrator.reset.grace.seconds=${ORCHESTRATOR_RESET_GRACE_SECONDS:15}
