quarkus.swagger-ui.always-include=true

# VIN this BRAKENOW instance is responsible for
brakenow.vin=${BRAKENOW_VIN:D2S-DEMO-VIN-002}

rabbitmq-host=${RABBITMQ_HOST:localhost}
rabbitmq-port=${RABBITMQ_PORT:5672}
rabbitmq-username=${RABBITMQ_USERNAME:dse}
rabbitmq-password=${RABBITMQ_PASSWORD:dse}

mp.messaging.incoming.vehicle-sonar.connector=smallrye-rabbitmq
mp.messaging.incoming.vehicle-sonar.exchange.name=d2s.vehicle.distance
mp.messaging.incoming.vehicle-sonar.queue.name=brakenow.sonar
mp.messaging.incoming.vehicle-sonar.routing-key=distance

mp.messaging.outgoing.brake-in.connector=smallrye-rabbitmq
mp.messaging.outgoing.brake-in.exchange.name=d2s.vehicle.brake
mp.messaging.outgoing.brake-in.routing-key=brake
