quarkus.swagger-ui.always-include=true

# VIN this BRAKENOW instance is responsible for
brakenow.vin=${BRAKENOW_VIN:D2S-DEMO-VIN-002}

rabbitmq-host=${RABBITMQ_HOST:localhost}
rabbitmq-port=${RABBITMQ_PORT:5672}
rabbitmq-username=${RABBITMQ_USERNAME:dse}
rabbitmq-password=${RABBITMQ_PASSWORD:dse}

# Incoming: SonarReadingDto from SONAR
mp.messaging.incoming.sonar-readings.connector=smallrye-rabbitmq
mp.messaging.incoming.sonar-readings.exchange.name=vehicle.sonar
mp.messaging.incoming.sonar-readings.queue.name=brakenow.sonar
mp.messaging.incoming.sonar-readings.routing-key=sonar

# Outgoing: BrakeMessage to ORCHESTRATOR
mp.messaging.outgoing.brake-status.connector=smallrye-rabbitmq
mp.messaging.outgoing.brake-status.exchange.name=d2s.vehicle.brake
mp.messaging.outgoing.brake-status.routing-key=brake
