quarkus.rest-client.utracked.url=${UTRACKED_URL:http://localhost:8086}
quarkus.rest-client.utracked.scope=jakarta.inject.Singleton

quarkus.rest-client.orchestrator.url=${ORCHESTRATOR_URL:http://localhost:8082}
quarkus.rest-client.orchestrator.scope=jakarta.inject.Singleton
