# Swagger UI — enabled in production for submission interview demo
quarkus.swagger-ui.always-include=true

# gRPC
quarkus.grpc.clients.orchestrator.host=${ORCHESTRATOR_GRPC_HOST:localhost}
quarkus.grpc.clients.orchestrator.port=${ORCHESTRATOR_GRPC_PORT:9001}
quarkus.grpc.clients.orchestrator.plain-text=true

quarkus.grpc.clients.utracked.host=${UTRACKED_GRPC_HOST:localhost}
quarkus.grpc.clients.utracked.port=${UTRACKED_GRPC_PORT:9002}
quarkus.grpc.clients.utracked.plain-text=true

quarkus.grpc.clients.sonar.host=${SONAR_GRPC_HOST:localhost}
quarkus.grpc.clients.sonar.port=${SONAR_GRPC_PORT:9003}
quarkus.grpc.clients.sonar.plain-text=true
