quarkus.rest-client.utracked.url=${UTRACKED_URL:http://localhost:8086}
quarkus.rest-client.utracked.scope=jakarta.inject.Singleton

# gRPC
quarkus.grpc.clients.orchestrator.host=${ORCHESTRATOR_GRPC_HOST:localhost}
quarkus.grpc.clients.orchestrator.port=${ORCHESTRATOR_GRPC_PORT:9001}
quarkus.grpc.clients.orchestrator.plain-text=true