# Database
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME:dse}
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD:dse}
quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL:jdbc:postgresql://localhost:5432/utracked}
quarkus.hibernate-orm.schema-management.strategy=${HIBERNATE_SCHEMA_STRATEGY:drop-and-create}

# RabbitMQ
rabbitmq-host=${RABBITMQ_HOST:localhost}
rabbitmq-port=${RABBITMQ_PORT:5672}
rabbitmq-username=${RABBITMQ_USERNAME:dse}
rabbitmq-password=${RABBITMQ_PASSWORD:dse}
mp.messaging.incoming.vehicle-position.connector=smallrye-rabbitmq
mp.messaging.incoming.vehicle-position.exchange.name=d2s.vehicle.gps
mp.messaging.incoming.vehicle-position.queue.name=utracked.gps
mp.messaging.incoming.vehicle-position.routing-key=gps

mp.messaging.incoming.scenario-command.connector=smallrye-rabbitmq
mp.messaging.incoming.scenario-command.exchange.name=d2s.simulator.scenario
mp.messaging.incoming.scenario-command.exchange.type=fanout
mp.messaging.incoming.scenario-command.queue.name=${UTRACKED_SCENARIO_QUEUE_NAME:utracked.scenario}
mp.messaging.incoming.scenario-command.routing-key=scenario
