services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: dse
      POSTGRES_PASSWORD: dse
      POSTGRES_DB: utracked
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  pgdata:
