apiVersion: v1
kind: ConfigMap
metadata:
  name: infra-config
data:
  rmq-url: "rabbitmq"
  rmq-port: "5672"

  database-url-orchestrator: "jdbc:postgresql://postgres:5432/orchestrator"
  database-url-utracked: "jdbc:postgresql://postgres:5432/utracked"
